# Generated by Django 5.2.5 on 2025-09-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id_youtube',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
