# Generated by Django 5.2.5 on 2025-08-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Portada',
                'verbose_name_plural': 'Portadas',
                'db_table': 'portadas',
            },
        ),
    ]
