# Generated by Django 5.2.5 on 2025-08-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Docente',
        ),
    ]
